apiVersion: apps/v1
kind: Deployment
metadata:
  name: magiclosapp
  namespace: api
  annotations:
    fluxcd.io/automated: "true"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: magiclosapp
  template:
    metadata:
      labels:
        app: magiclosapp
    spec:
      nodeSelector:
          nodegroup-type: api-workers
      # hostNetwork: true
      containers:
      - image: 048815747800.dkr.ecr.us-east-1.amazonaws.com/magic-losapp:6ca4f22
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
        imagePullPolicy: IfNotPresent
        name: "magiclosapp"
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=wwldv004.magic-dev.corp.amway.net)(PORT=9311)))(CONNECT_DATA=(SERVICE_NAME=wwbdv004)(SERVER=DEDICATED)))"
          - name: SPRING_DATASOURCE_USERNAME
            value: "cmndbxsuno"
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: devdbpass
                key: password
          - name: EXTREME_ENVIRONMENT
            value: "beta"
          - name: EXTREME_BOOTSTRAP_SERVER_LIST
            value: "uslxcd2101.intranet.local:2810,uslxcd2102.intranet.local:2810"
          - name: CACHE_ENABLED
            value: "true"
          - name: LOS_AUTH_API
            value: "http://magic-beta/EBS_UI_Service/rest/v2/LOSAuthorization/isAuthorized"
          - name: LOS_API_ENV
            value: "beta"
          - name: LOS_LITE_API_ENV
            value: "betalite"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: magiclosapp
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: magiclosapp
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75
---
apiVersion: v1
kind: Service
metadata:
  name: magiclosapp
  namespace: api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: "magiclosapp"
